
package com.emtech.service.itax.tcs.kra.pg.facade.impl;

import org.springframework.ws.WebServiceException;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

//impl.facade.pg.kra.tcs.com
//com.tcs.kra.pg.facade.impl
/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "KRAPaymentGatewayService", targetNamespace = "http://impl.facade.pg.kra.tcs.com/", wsdlLocation = "file:/home/emukule/Downloads/KRAPaymentGateway.wsdl")
public class KRAPaymentGatewayService
    extends Service
{

    private final static URL KRAPAYMENTGATEWAYSERVICE_WSDL_LOCATION;
    private final static WebServiceException KRAPAYMENTGATEWAYSERVICE_EXCEPTION;
    private final static QName KRAPAYMENTGATEWAYSERVICE_QNAME = new QName("http://impl.facade.pg.kra.tcs.com/", "KRAPaymentGatewayService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/emukule/Downloads/KRAPaymentGateway.wsdl");
        } catch (MalformedURLException ex) {
            //e = new WebServiceException(ex);
        }
        KRAPAYMENTGATEWAYSERVICE_WSDL_LOCATION = url;
        KRAPAYMENTGATEWAYSERVICE_EXCEPTION = e;
    }

    public KRAPaymentGatewayService() {
        super(__getWsdlLocation(), KRAPAYMENTGATEWAYSERVICE_QNAME);
    }

    public KRAPaymentGatewayService(WebServiceFeature... features) {
        super(__getWsdlLocation(), KRAPAYMENTGATEWAYSERVICE_QNAME, features);
    }

    public KRAPaymentGatewayService(URL wsdlLocation) {
        super(wsdlLocation, KRAPAYMENTGATEWAYSERVICE_QNAME);
    }

    public KRAPaymentGatewayService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, KRAPAYMENTGATEWAYSERVICE_QNAME, features);
    }

    public KRAPaymentGatewayService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KRAPaymentGatewayService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns KRAPaymentGateway
     */
    @WebEndpoint(name = "KRAPaymentGatewayPort")
    public KRAPaymentGateway getKRAPaymentGatewayPort() {
        return super.getPort(new QName("http://impl.facade.pg.kra.tcs.com/", "KRAPaymentGatewayPort"), KRAPaymentGateway.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KRAPaymentGateway
     */
    @WebEndpoint(name = "KRAPaymentGatewayPort")
    public KRAPaymentGateway getKRAPaymentGatewayPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.facade.pg.kra.tcs.com/", "KRAPaymentGatewayPort"), KRAPaymentGateway.class, features);
    }

    private static URL __getWsdlLocation() {
        if (KRAPAYMENTGATEWAYSERVICE_EXCEPTION!= null) {
            throw KRAPAYMENTGATEWAYSERVICE_EXCEPTION;
        }
        return KRAPAYMENTGATEWAYSERVICE_WSDL_LOCATION;
    }

}
