
package com.emtech.service.itax.tcs.kra.pg.facade.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "KRAPaymentGateway", targetNamespace = "http://impl.facade.pg.kra.tcs.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface KRAPaymentGateway {


    /**
     * 
     * @param ccrspayment
     * @param password
     * @param loginId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "eslipStatus", targetNamespace = "")
    @RequestWrapper(localName = "acceptPayment", targetNamespace = "http://impl.facade.pg.kra.tcs.com/", className = "com.tcs.kra.pg.facade.impl.AcceptPayment")
    @ResponseWrapper(localName = "acceptPaymentResponse", targetNamespace = "http://impl.facade.pg.kra.tcs.com/", className = "com.tcs.kra.pg.facade.impl.AcceptPaymentResponse")
    public String acceptPayment(
        @WebParam(name = "loginId", targetNamespace = "")
        String loginId,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "CCRSPAYMENT", targetNamespace = "")
        String ccrspayment);

    /**
     * 
     * @param password
     * @param eSlipNumber
     * @param loginId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "paymentEslip", targetNamespace = "")
    @RequestWrapper(localName = "checkEslip", targetNamespace = "http://impl.facade.pg.kra.tcs.com/", className = "com.tcs.kra.pg.facade.impl.CheckEslip")
    @ResponseWrapper(localName = "checkEslipResponse", targetNamespace = "http://impl.facade.pg.kra.tcs.com/", className = "com.tcs.kra.pg.facade.impl.CheckEslipResponse")
    public String checkEslip(
        @WebParam(name = "loginId", targetNamespace = "")
        String loginId,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "eSlipNumber", targetNamespace = "")
        String eSlipNumber);

}
